name: Build Native

on: workflow_dispatch

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: CMake configure
        run: cmake -B release -G Ninja GenerateBindings -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: ninja -C release

      - name: Archive build result
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: release/libminiaudio.so
